# Generated by Django 4.2.2 on 2024-10-24 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="cost",
            new_name="price",
        ),
    ]
